version: "3.9"
services:
  tooling_frontend:
    build: .
    ports:
      - "5000:80"
    volumes:
      - tooling_frontend:/var/www/html
    links:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: toolingdb
      MYSQL_USER: userconnect
      MYSQL_PASSWORD: zigali
      MYSQL_RANDOM_ROOT_PASSWORD: osla
    volumes:
      - db:/var/lib/mysql

networks:
  default:
    external:
      name: tooling_app_network

volumes:
  tooling_frontend:
  db: